### ISSUE TITLE
Non descriptive error with double period

### ISSUE THREAD

**Issue by mokkabonna** [marijnh/tern_for_sublime#63]
![image](https://cloud.githubusercontent.com/assets/230877/6426159/887714a4-bf4c-11e4-8796-d3a56698ad21.png)

Whenever I have something like window.body, and place the cursor after window (and before the period) and then type another period I get the error message in the screenshot. There is no output in the console.

**Comment by marijnh** [comment]
This was a bug in Acorn, which has been fixed a while ago. I've just pushed out Tern 0.9.0, which depends on a fixed Acorn version.

**Comment by Spaxe** [comment]
<img width="532" alt="screen shot 2019-02-07 at 10 03 27" src="https://user-images.githubusercontent.com/708395/52379897-ef18a280-2abf-11e9-9db0-48bc93bd76b2.png">
 
The bug is back - I'm on tern_for_sublime v2019-01-24. Any ideas why it's back?
